[package]
name = "blender"
version = "0.1.0"
edition = "2021"

# trying something out, make this library once I can understand how I can reference this externally from tauri side of application
# [lib]
# crate-type = ["cdylib"]

[dependencies]
dirs = "6.0.0"
regex = "^1.11.1"
semver = { version = "^1.0", features = ["serde"] }
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
url = { version = "^2.5.4", features = ["serde"] }
thiserror = "^2.0"
uuid = { version = "^1.20", features = ["serde", "v4"] }
ureq = { version = "^3.0" }
blend = "0.8.0"
tokio = { version = "^1.49", features = ["full"] }
# xml-rpc will merge into this project some day in the future, as it's just a http server protocol.
xml-rpc = { git = "https://github.com/tiberiumboy/xml-rpc-rs.git" }

[target.'cfg(target_os = "windows")'.dependencies]
zip = "^7"

[target.'cfg(target_os = "macos")'.dependencies]
dmg = { version = "^0.1" }

[target.'cfg(target_os = "linux")'.dependencies]
xz = { version = "^0.1" }
tar = { version = "^0.4" }
