[package]
name = "blendfarm"
"authors" = ["Jordan Bejar"]
description = "A open-source, cross-platform, stand-alone Network Render farm for Blender"
license = "MIT"
repository = "https://github.com/tiberiumboy/BlendFarm"
edition = "2021"
version = "0.1.0"

[lib]
name = "blenderfarm_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[build-dependencies]
# prost-build = "0.13.3"
tauri-build = { version = "^2.0.1", features = [] }

[dependencies]
anyhow = "^1.0"
async-trait = "0.1.83"
async-std = "1.13.0"
blend = "0.8.0"
blender = { path = "./../blender/" }
libp2p = { version = "^0.54", features = [
    "mdns",
    "macros",
    "gossipsub",
    "noise",
    "ping",
    "tcp",
    "tokio",
    "yamux",
    "tls",
    "quic",
    "kad",
    "request-response",
] }
bincode = "1.3.3"
dirs = "5.0.1"
pnet = "^0.35"
semver = "^1.0"
machine-info = "*"
thiserror = "*"
tauri-cli = "^2.1"
tauri-plugin-core = "2.0.0-beta.0"
tauri-plugin-dialog = "^2.0"
tauri-plugin-fs = "^2.0"
tauri-plugin-os = "^2.0"
tauri-plugin-persisted-scope = "^2.0"
tauri-plugin-shell = "^2.0"
tokio = { version = "^1.41", features = ["full"] }
quinn = "^0.11"
tracing = "^0.1"
tracing-subscriber = { version = "^0.3", features = ["env-filter"] }
clap = "4.5.21"

# this came autogenerated. I don't think I will develop this in the future, but would consider this as an april fools joke. Yes I totally would.
[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-cli = "^2"
tauri = { version = "^2.0", features = ["protocol-asset"] }
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
uuid = { version = "^1.10", features = [
    "v4",
    "fast-rng",
    "macro-diagnostics",
    "serde",
] }
