[package]
name = "blendfarm"
version = "0.1.0"
description = "A open-source, cross-platform, stand-alone Network Renderer for Blender, in rust"
authors = ["Jordan Bejar"]
license = "MIT"
repository = ""
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.5", features = [] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dependencies]
gethostname = "*"
blender = { path = "../blender" }
tauri = { version = "1.5", features = ["api-all"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
# libc = "*"
# clap = "*"
message-io = { version = "0.18", default-features = false, features = [
    "tcp",
    "udp",
] }
bincode = "1.3.3"
thiserror = "1.0.58"
semver = "1.0.22"
# url = "2.5.0"
regex = "1.10.4"
dirs = "5.0.1"
anyhow = "1.0.86"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]

[dependendies.uuid]
version = "1.7.0"
features = ["v4", "fast-rng", "macro-diagnostics"]

[dependendies.pnet]
version = "0.34"
