/*
    Developer Blog:
    - Original idea behind this was to use PhantomData to mitigate the status of the job instead of reading from enum.
        Need to refresh materials about PhantomData, and how I can translate this data information for front end to update/reflect changes
        The idea is to change the struct to have state of the job.
        I think the limitation for this is serialization/deserialization property.
    - I need to fetch the handles so that I can maintain and monitor all node activity.
    - The Job will have similar state machines.
        - First state is to fetch info about this job and related task from all nodes on the network.
        - Then Reconciliate with the existing image stored locally.
        - Afterward, collect linkage to path, any missing remaining will create a new task and send to pools of pending task to distribute
        - This job will routinely checks on all task generated by varioius node.   
    - TODO: See about migrating Sender code into this module?
*/
use super::ticket::Ticket;
use super::with_id::WithId;
use crate::domains::job_store::JobError;
use crate::network::PeerIdString;
use blender::blender::Frame;
use blender::{blend_file::BlendFile, models::mode::RenderMode};
use futures::channel::mpsc::Sender;
use semver::Version;
use serde::{Deserialize, Serialize};
use std::{ffi::OsStr, path::Path};
use std::path::PathBuf;
use uuid::Uuid;

// TODO: I need to refactor this script so it's less code smell.
// I want to make this a better management system.
// The Job struct will contain the work order information.
// We have a require qty count to render to meet the work order quantity. 
// This work order can have multiple of Task, as long as the task have the following conditions: 
//      A) an newly existing node assigned to this task.
//      B) an node containing raw completed image for this job
//      C) successfully downloaded the image from the node + local reference instead. (End goal)
// This means that if a node was recently assigned to work on this job's task, but was cancel, both job and node should delete the task as no new information is savageable.   
// Any information created or stored will persist to local database for persistent storage and quick lookup. This can be handy in the future if we can get ffmpeg included.

// THIS IS TREATED AS NOTIFICATION UPDATES. DO NOT TAKE THIS AS COMMAND! Acknowledge the package and run behavior tree decision.
#[derive(Debug, Serialize, Deserialize )]
pub enum JobEvent {
    Render(PeerIdString, Ticket),
    Remove(Uuid),
    Failed(String),
    RequestTask,
    ImageCompleted {
        job_id: Uuid,
        frame: Frame,
        file_name: String,  // Could PathBuf be treated for file_name?
    },
    AskForCompletedJobFrameList(JobId),
    ImageCompletedList {
        job_id: JobId,
        files: Vec<String>,
    },
    
    TicketComplete(JobId, Frame), // what's the difference between JobComplete and TaskComplete?
    // Error(JobError), 
    // TODO: for now let's handle this error as string. Find a reason why we want to serialize error enums?
    Error(String)
}

#[derive(Debug)]
pub enum JobAction {
    Find(JobId, Sender<Option<CreatedJobDto>>),
    Update(CreatedJobDto),
    Create(NewJobDto, Sender<Result<CreatedJobDto, JobError>>),
    Kill(JobId),
    All(Sender<Option<Vec<CreatedJobDto>>>),
    // we will ask all of the node on the network if there's any completed job list.
    // The node will advertise their collection of completed job
    // the host will be responsible to compare with the current output files and
    // see if there's any missing job. If there is missing frame then
    // we will ask to fetch for that completed image back
    AskForCompletedList(JobId),
    Advertise(JobId),
}

// Used to ignore sender types comparsion. We do not care about sender equality.
impl PartialEq for JobAction {
    fn eq(&self, other: &Self) -> bool {
        match (self, other) {
            (Self::Find(l0, ..), Self::Find(r0, ..)) => l0 == r0,
            (Self::Update(l0), Self::Update(r0)) => l0.id == r0.id,
            (Self::Create(l0, ..), Self::Create(r0, ..)) => l0 == r0,
            (Self::Kill(l0), Self::Kill(r0)) => l0 == r0,
            (Self::All(..), Self::All(..)) => true,
            (Self::AskForCompletedList(l0), Self::AskForCompletedList(r0)) => l0 == r0,
            (Self::Advertise(l0), Self::Advertise(r0)) => l0 == r0,
            _ => false,
        }
    }
}

pub type JobId = Uuid;
pub type Output = PathBuf;
pub type NewJobDto = Job;
pub type CreatedJobDto = WithId<Job, JobId>;

// This job is created by the manager and will be used to help determine the individual task created for the workers
// we will derive this job into separate task for individual workers to process based on chunk size.
#[derive(Debug, Serialize, Deserialize, Clone, sqlx::FromRow, sqlx::Encode, sqlx::Decode)]
pub struct Job {
    /// contains the information to specify the kind of job to render (We could auto fill this from blender peek function?)
    mode: RenderMode,

    /// Path to blender files
    blend_file: BlendFile,

    // target blender version
    pub(crate) blender_version: Version,

    // target output destination
    output: Output,

    // List of task created by the runners This serves as a job history and transaction that perform the job
    tasks: Vec<Ticket>,
}

impl Job {
    // private - no validation, we trust that the validation is done from public api.
    fn new(
        mode: RenderMode,
        blend_file: BlendFile,
        blender_version: Version, // TODO: see if we can validate if this job uses the correct blender version
        output: Output,           // must be a valid directory
    ) -> Self {
        Self {
            mode,
            blend_file,
            blender_version,
            output,
            tasks: Vec::new(),
        }
    }

    /// Create a new job entry with provided all information intact. Used for holding database records
    pub fn from(
        mode: RenderMode,
        project_file: impl AsRef<Path>,
        version: Version,
        output: PathBuf,
    ) -> Result<Self, JobError> {
        match BlendFile::new(project_file) {
            Ok(file) => Ok(Job::new(mode, file, version, output)),
            Err(e) => Err(JobError::InvalidFile(e.to_string())),
        }
    }

    // Hmm Risky. Would consider promoting to higher application layer services.
    pub fn generate_task(self, job_id: Uuid) -> Option<Ticket> {
        // in this case, a job would have break up into pieces for worker client to receive and start a new job
        // first thing first, how can I tell if the job is completed or not?
        // in the future we will find a better mechanism to partition the frames up and distributed across network nodes.
        // If we have node requesting for new task, but we've completed exhaust the query range, we should check other nodes
        // and ask the highest queue frame for some of the frame counts instead, until we've reached to a certain water overflow threshold.
        let (start, end) = match &self.mode {
            RenderMode::Frame(v) => (v.to_owned(), v.to_owned()),
            RenderMode::Animation{start, end} => (start.to_owned(), end.to_owned()),
        };
        
        let job_record = WithId { id: job_id, item: self };

        match Ticket::from(job_record, start, end) {
            Ok(task) => Some(task),
            Err(e) => {
                println!("Unable to make task? {e:?}");
                None
            }
        }
    }

    pub fn get_file_name_expected(&self) -> &OsStr {
        self.blend_file
            .to_path()
            .file_name()
            .expect("Must have valid file name already")
    }
}

impl PartialEq for Job {
    fn eq(&self, other: &Self) -> bool {
        self.mode == other.mode
            && self.blend_file == other.blend_file
            && self.blender_version == other.blender_version
            && self.output == other.output
        // no need to compare job history for partial equal
        // && self.tasks == other.tasks
    }
}

impl AsRef<BlendFile> for Job {
    fn as_ref(&self) -> &BlendFile {
        &self.blend_file
    }
}

impl AsRef<Version> for Job {
    fn as_ref(&self) -> &Version {
        &self.blender_version
    }
}

/// return the job output destination (Should be used on the host machine)
impl AsRef<Output> for Job {
    fn as_ref(&self) -> &Output {
        &self.output
    }
}

impl AsRef<RenderMode> for Job {
    fn as_ref(&self) -> &RenderMode {
        &self.mode
    }
}

#[cfg(test)]
pub(crate) mod test {
    use super::*;
    use crate::models::constant::test::{EXAMPLE_FILE, EXAMPLE_OUTPUT};
    use std::path::Path;

    pub fn scaffold_job() -> Job {
        let mode = RenderMode::Frame(1);
        let file = Path::new(EXAMPLE_FILE);
        let project_file = BlendFile::new(file).expect("expect this to work without issue");
        let version = Version::new(4, 4, 0);
        let dir = Path::new(EXAMPLE_OUTPUT);
        let output = dir.to_path_buf();
        Job::new(mode, project_file, version, output)
    }

    // we should at least try to test it against public api
    #[test]
    fn create_job_successful() {
        let file = Path::new(EXAMPLE_FILE);
        let mode = RenderMode::Frame(1);
        let version = Version::new(1, 1, 1);
        let output = Path::new("./test/");
        let job = Job::from(mode.clone(), file, version.clone(), output.to_path_buf());

        let project_file = BlendFile::new(file).expect("Should be valid project file");

        assert!(job.is_ok());
        let job = job.unwrap();

        assert_eq!(job.mode, mode);
        assert_eq!(job.output, output);
        assert_eq!(AsRef::<BlendFile>::as_ref(&job), &project_file);
        assert_eq!(AsRef::<Version>::as_ref(&job), &version);
        assert_eq!(
            job.get_file_name_expected(),
            file.file_name()
                .expect("Should have valid file name")
                .to_str()
                .expect("Shoudl have valid file name!")
        );
    }

    #[test]
    fn invalid_project_file_path_should_fail() {}
}
