[package]
name = "blender"
version = "0.1.0"
edition = "2021"

[dependencies]
dirs = "5.0.1"
dmg = { version = "0.1.2" }
regex = "1.10.4"
semver = { version = "1.0.22", features = ["serde"] }
serde = { version = "1.0.198", features = ["derive"] }
serde_json = "1.0"
tar = { version = "0.4.40" }
url = { version = "2.5.0", features = ["serde"] }
xz = { version = "0.1.0" }
thiserror = "1.0.29"
uuid = { version = "1.10.0", features = ["serde", "v4"] }
ureq = { version = "2.10.1" }
zip = "2.2.0"


# [features]
# manager = ["ureq", "xz", "tar", "dmg"]
