[package]
name = "blender"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.10.4"
reqwest = { version = "0.12.4", features = ["blocking"] }
semver = { version = "1.0.22", features = ["serde"] }
serde = { version = "1.0.198", features = ["derive"] }
url = "2.5.0"
