[package]
name = "blender"
version = "0.1.0"
edition = "2021"

[dependencies]
dirs = "5.0.1"
dmg = "0.1.2"
regex = "1.10.4"
reqwest = { version = "0.12.4", features = ["blocking"] }
semver = { version = "1.0.22", features = ["serde"] }
serde = { version = "1.0.198", features = ["derive"] }
serde_json = "1.0"
tar = "0.4.40"
url = "2.5.0"
xz = "0.1.0"
thiserror = "1.0.29"